projects:
  My AppSync App:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-west-2
        apiId: xj3ttibogvgm5ohjjvpo7y4bme
        maxDepth: 2
extensions:
  amplify:
    version: 3
